### ISSUE TITLE
Hope for adding the lang-switch tool.

### ISSUE THREAD

**Issue by ChengYueJia** [funkill/mdbook-i18n#22]

**Comment by ChengYueJia** [comment]
For now, we can't switch the lang. 

Thanks for dev the tool, maybe we can enhance it.

**Comment by funkill** [comment]
Hi!

Maybe for now [theme](https://github.com/funkill/mdbook-i18n/blob/master/example/theme/index.hbs) from example helps you? Example deployed [here](https://funkill.github.io/mdbook-i18n/en/), switch button near print button.

Currently automatic generation of lang switcher not implemented :(

**Comment by ChengYueJia** [comment]
Thx for that. It does help me a lot. I've tried it on a mdbook-docs.

The style seems a little bit wrong. The title of chapter is shadowed. Not like what in your [demo](https://funkill.github.io/mdbook-i18n/ru/)

![image](https://user-images.githubusercontent.com/108982045/194698776-ef16da3b-1f47-419c-9345-7290b156c10e.png)

![image](https://user-images.githubusercontent.com/108982045/194698863-606f6b26-1b86-42f4-afbd-ef2d2d7c9826.png)


You can try it on my ph-page.https://chengyuejia.github.io/move/en/conditionals.html.
And the source code is [here](https://github.com/ChengYueJia/move/tree/main/language/documentation/book)

**Comment by ChengYueJia** [comment]
Wow, Thanks a lot to help me. I'll merge it.

So sad to know mdbook can't support the auto-generated lang-switcher script.

There will be  other way to make it.
As a script can auto modify or generate the theme  files account to the .toml files. ? LoL 

The mdbook-i18n is greet. You already did a great job , It's helps me a lot , and will help more projects.
